spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: cluster-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/clusters/**

        - id: node-service-cluster-nodes
          uri: http://localhost:8082
          predicates:
            - Path=/api/clusters/*/nodes/**

        - id: node-service-all-nodes
          uri: http://localhost:8082
          predicates:
            - Path=/api/nodes/**

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty: INFO