spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: node-service-cluster-nodes
          uri: ${NODE_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/clusters/*/nodes/**

        - id: cluster-service
          uri: ${CLUSTER_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/clusters/**

        - id: node-service-all-nodes
          uri: ${NODE_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/nodes/**

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty: INFO
