spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://cluster-db:5432/clusterdb}
    username: ${SPRING_DATASOURCE_USERNAME:clusteruser}
    password: ${SPRING_DATASOURCE_PASSWORD:clusterpass}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka/}
  instance:
    instance-id: ${spring.application.name}:${INSTANCE_ID:${random.value}}
    prefer-ip-address: true

node:
  service:
    url: http://node-service